export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';

export const INCREMENT_POST_LIKES_REQUEST = 'INCREMENT_POST_LIKES_REQUEST';
export const INCREMENT_POST_LIKES_ERROR = 'INCREMENT_POST_LIKES_ERROR';
export const INCREMENT_POST_LIKES_SUCCESS = 'INCREMENT_POST_LIKES_SUCCESS';
