export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';

export const INCREMENT_POSTS_LIKES_REQUEST = 'INCREMENT_POSTS_LIKES_REQUEST';
export const INCREMENT_POSTS_LIKES_ERROR = 'INCREMENT_POSTS_LIKES_ERROR';
export const INCREMENT_POSTS_LIKES_SUCCESS = 'INCREMENT_POSTS_LIKES_SUCCESS';
